# Generated by Django 5.1.3 on 2025-08-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_seekerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
