# Generated by Django 5.1.3 on 2025-08-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='job.skill'),
        ),
    ]
