# Generated by Django 5.1.3 on 2025-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_skill_job_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.skill'),
        ),
    ]
