# Generated by Django 5.1.3 on 2025-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.skill'),
        ),
    ]
