# Generated by Django 5.1.3 on 2025-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_seekerprofile_skills_seekerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
