# Generated by Django 5.1.3 on 2025-08-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_seekerprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='experience',
        ),
    ]
