# Generated by Django 5.1.3 on 2025-08-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_seekerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.seekerprofile'),
        ),
    ]
