# Generated by Django 5.1.3 on 2025-09-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
